=== MarcosMirandaDam/JAXBImpresoras/impresoras.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Jose Arias (Educastur) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="sistemasImpresion">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="impresoras">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="impresora" type="impresoraType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="cartuchos">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="cartucho" type="cartuchoType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="marcas">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="marca" type="marcaType"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="impresoraType">
		<xs:sequence>
			<xs:element name="marca" type="marcaType"/>
			<xs:element name="modelo">
				<xs:complexType>
					<xs:attribute name="descatalogado" type="xs:boolean"/>
				</xs:complexType>
			</xs:element>
			<xs:element name="precio" type="xs:int"/>
			<xs:element name="fechaSalida" type="xs:date"/>
			<xs:element name="cartuchosCompatibles">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="cartucho" type="cartuchoType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="cartuchoType">
		<xs:sequence>
			<xs:element name="modeloCartucho" type="xs:string"/>
			<xs:element name="descripcion" type="xs:string"/>
			<xs:element name="nombreMarca" type="xs:string"/>
			<xs:element name="maxPaginas" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="marcaType">
		<xs:sequence>
			<xs:element name="nombre" type="xs:string"/>
			<xs:element name="telefono" type="xs:integer"/>
			<xs:element name="correoE" type="xs:string"/>
			<xs:element name="direccion" type="direccionType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="direccionType">
		<xs:sequence>
			<xs:element name="calle" type="xs:string"/>
			<xs:element name="poblacion" type="xs:string"/>
			<xs:element name="cp" type="xs:integer"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== MarcosMirandaDam/JAXBImpresoras/impresoras.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2011 sp1 (http://www.altova.com)-->
<sistemasImpresion xsi:noNamespaceSchemaLocation="impresoras.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<impresoras>
		<impresora>
			<marca>
				<nombre>Canon</nombre>
				<telefono>985662735</telefono>
				<correoE>sssocram@gmail.com</correoE>
                                <direccion>la vega</direccion>
			</marca>
			<modelo descatalogado="true"/>
			<precio>399</precio>
			<fechaSalida>1967-08-13</fechaSalida>
			<cartuchosCompatibles>
				<cartuchos>
					<marca>
                                            <modeloCartucho>PowerLink</modeloCartucho>
						<telefono>985662736</telefono>
						<correoE>aaanairam@gmail.com</correoE>
					</marca>
					<modelo>1234</modelo>
					<maxPaginas>5000</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>TintaMax</nombre>
						<telefono>636146896</telefono>
						<correoE>sssocram@gmail.com</correoE>
					</marca>
					<modelo>1000XF</modelo>
					<maxPaginas>3000</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>Nisu</nombre>
						<telefono>985454578</telefono>
						<correoE>sssocram@gmail.com</correoE>
					</marca>
					<modelo>PowerMaxim</modelo>
					<maxPaginas>7500</maxPaginas>
				</cartuchos>
			</cartuchosCompatibles>
		</impresora>
		<impresora>
			<marca>
				<nombre>HP</nombre>
				<telefono>91565747</telefono>
				<correoE>hp@cliente.com</correoE>
			</marca>
			<modelo descatalogado="true"/>
			<precio>699</precio>
			<fechaSalida>1967-08-13</fechaSalida>
			<cartuchosCompatibles>
				<cartuchos>
					<marca>
						<nombre>hpLink</nombre>
						<telefono>123321321</telefono>
						<correoE>hp@cliente.com</correoE>
					</marca>
					<modelo>2500max</modelo>
					<maxPaginas>6000</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>hpPlus</nombre>
						<telefono>123321321</telefono>
						<correoE>hp@cliente.com</correoE>
					</marca>
					<modelo>plus2500</modelo>
					<maxPaginas>1500</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>hpAhorro</nombre>
						<telefono>123321321</telefono>
						<correoE>hp@cliente.com</correoE>
					</marca>
					<modelo>ahorroDia</modelo>
					<maxPaginas>15000</maxPaginas>
				</cartuchos>
			</cartuchosCompatibles>
		</impresora>
		<impresora>
			<marca>
				<nombre>String</nombre>
				<telefono>0</telefono>
				<correoE>String</correoE>
			</marca>
			<modelo descatalogado="true"/>
			<precio>0</precio>
			<fechaSalida>1967-08-13</fechaSalida>
			<cartuchosCompatibles>
				<cartuchos>
					<marca>
						<nombre>String</nombre>
						<telefono>0</telefono>
						<correoE>String</correoE>
					</marca>
					<modelo>String</modelo>
					<maxPaginas>0</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>String</nombre>
						<telefono>0</telefono>
						<correoE>String</correoE>
					</marca>
					<modelo>String</modelo>
					<maxPaginas>0</maxPaginas>
				</cartuchos>
				<cartuchos>
					<marca>
						<nombre>String</nombre>
						<telefono>0</telefono>
						<correoE>String</correoE>
					</marca>
					<modelo>String</modelo>
					<maxPaginas>0</maxPaginas>
				</cartuchos>
			</cartuchosCompatibles>
		</impresora>
	</impresoras>
	<cartuchos>
		<cartucho>
			<marca>
				<nombre>String</nombre>
				<telefono>0</telefono>
				<correoE>String</correoE>
			</marca>
			<modelo>String</modelo>
			<maxPaginas>0</maxPaginas>
		</cartucho>
		<cartucho>
			<marca>
				<nombre>String</nombre>
				<telefono>0</telefono>
				<correoE>String</correoE>
			</marca>
			<modelo>String</modelo>
			<maxPaginas>0</maxPaginas>
		</cartucho>
		<cartucho>
			<marca>
				<nombre>String</nombre>
				<telefono>0</telefono>
				<correoE>String</correoE>
			</marca>
			<modelo>String</modelo>
			<maxPaginas>0</maxPaginas>
		</cartucho>
	</cartuchos>
	<marcas>
		<marca>
			<nombre>String</nombre>
			<telefono>0</telefono>
			<correoE>String</correoE>
		</marca>
		<marca>
			<nombre>String</nombre>
			<telefono>0</telefono>
			<correoE>String</correoE>
		</marca>
		<marca>
			<nombre>String</nombre>
			<telefono>0</telefono>
			<correoE>String</correoE>
		</marca>
	</marcas>
</sistemasImpresion>
